# Generated by Django 2.0.4 on 2018-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('author_id', models.PositiveIntegerField()),
                ('dynasty', models.CharField(blank=True, max_length=10, null=True)),
                ('author', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'poems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoemsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intro_l', models.TextField(blank=True, null=True)),
                ('intro_s', models.TextField()),
                ('dynasty', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'poems_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('yunlv_rule', models.TextField()),
                ('author_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('dynasty', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'poetry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoetryAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('intro', models.TextField(blank=True, null=True)),
                ('dynasty', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'poetry_author',
                'managed': False,
            },
        ),
    ]
