# Generated by Django 2.0.4 on 2018-08-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poemsauthor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poetry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poetryauthor',
            options={},
        ),
    ]
